// 自动生成（verif/sta/probe/gen_dcache_geo_wrappers.py）：dcache 几何采样包装
// 参数：BLOCK_SIZE=64, CACHE_SIZE=8192, GROUP_NUM=2（SRAM 未例化/黑盒）
module ysyx_22040750_probe_dcache_geo_A(
  input clk, input rst,
  input [31:0] I_cpu_addr,
  input [63:0] I_cpu_data,
  input [7:0] I_cpu_wmask,
  input [7:0] I_cpu_rmask,
  input I_cpu_rd_req,
  input I_cpu_wr_req,
  output O_cpu_mem_ready,
  input I_cpu_fencei,
  output O_dcache_clean,
  input [512-1:0] I_way0_rdata,
  input [512-1:0] I_way1_rdata,
  output [5:0] O_sram_addr,
  output [3:0] O_sram_cen,
  output [3:0] O_sram_wen,
  output [512-1:0] O_sram_wdata,
  output [512-1:0] O_sram_wmask,
  input [63:0] I_mem_rdata,
  input I_mem_arready,
  input I_mem_rvalid,
  input I_mem_rlast,
  output [31:0] O_mem_araddr,
  output O_mem_arvalid,
  output O_mem_rready,
  output [7:0] O_mem_arlen,
  output [2:0] O_mem_arsize,
  output [1:0] O_mem_arburst,
  input I_mem_awready,
  input I_mem_wready,
  input I_mem_bvalid,
  output [63:0] O_mem_wdata,
  output [31:0] O_mem_awaddr,
  output O_mem_awvalid,
  output O_mem_wvalid,
  output O_mem_bready,
  output O_mem_wlast,
  output [7:0] O_mem_awlen,
  output [2:0] O_mem_awsize,
  output [1:0] O_mem_awburst,
  output [7:0] O_mem_wstrb,
  output [63:0] O_cpu_data,
  output O_cpu_rvalid,
  output O_cpu_bvalid
);
  ysyx_22040750_dcachectrl #(.BLOCK_SIZE(64), .CACHE_SIZE(8192), .GROUP_NUM(2)) u_dut (
    .I_clk(clk),
    .I_rst(rst),
    .I_cpu_addr(I_cpu_addr),
    .I_cpu_data(I_cpu_data),
    .I_cpu_wmask(I_cpu_wmask),
    .I_cpu_rmask(I_cpu_rmask),
    .I_cpu_rd_req(I_cpu_rd_req),
    .I_cpu_wr_req(I_cpu_wr_req),
    .O_cpu_mem_ready(O_cpu_mem_ready),
    .I_cpu_fencei(I_cpu_fencei),
    .O_dcache_clean(O_dcache_clean),
    .I_way0_rdata(I_way0_rdata),
    .I_way1_rdata(I_way1_rdata),
    .O_sram_addr(O_sram_addr),
    .O_sram_cen(O_sram_cen),
    .O_sram_wen(O_sram_wen),
    .O_sram_wdata(O_sram_wdata),
    .O_sram_wmask(O_sram_wmask),
    .I_mem_rdata(I_mem_rdata),
    .I_mem_arready(I_mem_arready),
    .I_mem_rvalid(I_mem_rvalid),
    .I_mem_rlast(I_mem_rlast),
    .O_mem_araddr(O_mem_araddr),
    .O_mem_arvalid(O_mem_arvalid),
    .O_mem_rready(O_mem_rready),
    .O_mem_arlen(O_mem_arlen),
    .O_mem_arsize(O_mem_arsize),
    .O_mem_arburst(O_mem_arburst),
    .I_mem_awready(I_mem_awready),
    .I_mem_wready(I_mem_wready),
    .I_mem_bvalid(I_mem_bvalid),
    .O_mem_wdata(O_mem_wdata),
    .O_mem_awaddr(O_mem_awaddr),
    .O_mem_awvalid(O_mem_awvalid),
    .O_mem_wvalid(O_mem_wvalid),
    .O_mem_bready(O_mem_bready),
    .O_mem_wlast(O_mem_wlast),
    .O_mem_awlen(O_mem_awlen),
    .O_mem_awsize(O_mem_awsize),
    .O_mem_awburst(O_mem_awburst),
    .O_mem_wstrb(O_mem_wstrb),
    .O_cpu_data(O_cpu_data),
    .O_cpu_rvalid(O_cpu_rvalid),
    .O_cpu_bvalid(O_cpu_bvalid)
  );
endmodule
